apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/shop-backend:latest
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: shop-secrets
                  key: DB_URI
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: shop-secrets
                  key: JWT_SECRET_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: shop-secrets
                  key: REDIS_URL